### ISSUE TITLE
XL benchmark aborts: [ERROR] Failed to load graph ""datagen-sf3k-fb:datagen-sf3k-fb.e_weight"".

### ISSUE THREAD

**Issue by hagabb** [FTSRG/ldbc-graphalytics#38]
The S, M, and L benchmarks ran correctly but the XL benchmark fails with the messages below. My ldbc_graphalytics_platforms_graphblas and ldbc_graphalytics repos are up to date. Any ideas?

08:57 [INFO ] Preparing graph "datagen-sf3k-fb" with 2 different formats: [datagen-sf3k-fb, datagen-sf3k-fb.e_weight]
08:57 [INFO ]
08:57 [INFO ]
08:57 [INFO ] Preprocessing graph "datagen-sf3k-fb:datagen-sf3k-fb.e_weight" for 1 benchmark run(s).
08:57 [INFO ] Formatting (Minimizing) graph ""datagen-sf3k-fb:datagen-sf3k-fb.e_weight""
08:57 [INFO ] Found edge file for graph "datagen-sf3k-fb.e_weight" at "/home/devcloud/graphalytics_data/XL/datagen-sf3k-fb.e".
08:57 [INFO ] Formatted (Minimizing) graph ""datagen-sf3k-fb:datagen-sf3k-fb.e_weight""
08:57 [INFO ] ----------------- Loading graph ""datagen-sf3k-fb:datagen-sf3k-fb.e_weight"" -----------------
08:57 [INFO ] Loading graph datagen-sf3k-fb.e_weight
08:57 [INFO ] Execute graph loader with command-line: [/home/devcloud/ldbc_graphalytics_platforms_graphblas/graphalytics-1.10.0-graphblas-0.1.0-SNAPSHOT/./bin/sh/load-graph.sh --graph-name datagen-sf3k-fb.e_weight --input-vertex-path /home/devcloud/graphalytics_data/XL/datagen-sf3k-fb.v --input-edge-path /home/devcloud/graphalytics_data/XL/datagen-sf3k-fb.e --output-path ./intermediate/datagen-sf3k-fb.e_weight --directed false --weighted true]
Loading...
Relabelling...
Serializing textual mapping file (vtx)
Serializing textual matrix file (mtx)
/home/devcloud/ldbc_graphalytics_platforms_graphblas/graphalytics-1.10.0-graphblas-0.1.0-SNAPSHOT/./bin/sh/load-graph.sh: line 67: 438805 Killed                  bin/exe/converter --data-dir ${OUTPUT_PATH}
09:37 [ERROR] Failed to load graph ""datagen-sf3k-fb:datagen-sf3k-fb.e_weight"".
 science.atlarge.graphalytics.execution.PlatformExecutionException: Failed to load a GraphBLAS dataset.
        at science.atlarge.graphalytics.graphblas.GraphblasPlatform.loadGraph(GraphblasPlatform.java:54) ~[graphalytics-platforms-graphblas-0.1.0-SNAPSHOT-default.jar:?]
        at science.atlarge.graphalytics.execution.BenchmarkExecutor.loadGraph(BenchmarkExecutor.java:375) [graphalytics-platforms-graphblas-0.1.0-SNAPSHOT-default.jar:?]
        at science.atlarge.graphalytics.execution.BenchmarkExecutor.execute(BenchmarkExecutor.java:132) [graphalytics-platforms-graphblas-0.1.0-SNAPSHOT-default.jar:?]
        at science.atlarge.graphalytics.BenchmarkSuite.main(BenchmarkSuite.java:107) [graphalytics-platforms-graphblas-0.1.0-SNAPSHOT-default.jar:?]
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 137 (Exit value: 137)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404) ~[graphalytics-platforms-graphblas-0.1.0-SNAPSHOT-default.jar:?]
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166) ~[graphalytics-platforms-graphblas-0.1.0-SNAPSHOT-default.jar:?]
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153) ~[graphalytics-platforms-graphblas-0.1.0-SNAPSHOT-default.jar:?]
        at science.atlarge.graphalytics.graphblas.GraphblasLoader.load(GraphblasLoader.java:64) ~[graphalytics-platforms-graphblas-0.1.0-SNAPSHOT-default.jar:?]
        at science.atlarge.graphalytics.graphblas.GraphblasPlatform.loadGraph(GraphblasPlatform.java:49) ~[graphalytics-platforms-graphblas-0.1.0-SNAPSHOT-default.jar:?]
        ... 3 more
09:37 [ERROR] Several error in Graphalytics execution: 1 benchmark runs are skipped.
09:37 [INFO ]
09:37 [INFO ]
09:37 [INFO ] ============= Start of benchmark r809270 [6/56] =============
09:37 [INFO ] Benchmark r809270 has failed ([DAT]), T_l=nan, T_m=nan, T_p=nan.
09:37 [INFO ] ============== End of benchmark r809270 [6/56] ==============
09:37 [INFO ]
09:37 [INFO ]
09:37 [INFO ] Deleting graph "datagen-sf3k-fb:datagen-sf3k-fb.e_weight".
09:37 [INFO ] ----------------- Deleting graph ""datagen-sf3k-fb:datagen-sf3k-fb.e_weight"" -----------------
09:37 [ERROR] Failed to delete graph "datagen-sf3k-fb:datagen-sf3k-fb.e_weight"
09:37 [ERROR] science.atlarge.graphalytics.configuration.GraphalyticsExecutionException: Fatal error in Graphalytics execution: the benchmark is aborted.
science.atlarge.graphalytics.configuration.GraphalyticsExecutionException: Fatal error in Graphalytics execution: the benchmark is aborted.
        at science.atlarge.graphalytics.execution.BenchmarkExecutor.deleteGraph(BenchmarkExecutor.java:391)
        at science.atlarge.graphalytics.execution.BenchmarkExecutor.execute(BenchmarkExecutor.java:217)
        at science.atlarge.graphalytics.BenchmarkSuite.main(BenchmarkSuite.java:107)
Caused by: java.lang.NullPointerException
        at science.atlarge.graphalytics.graphblas.GraphblasPlatform.deleteGraph(GraphblasPlatform.java:62)
        at science.atlarge.graphalytics.execution.BenchmarkExecutor.deleteGraph(BenchmarkExecutor.java:388)
        ... 2 more

**Comment by ghost** [comment]
The line after "Serializing textual matrix file (mtx)" mentions a killed process. Maybe it ran out of memory?

**Comment by hagabb** [comment]
It could have run out of memory if the XL benchmark requires more than 264 GB. The edge list for sf3k is 97 GB.

**Comment by szarnyasg** [comment]
This was likely an out of memory error.
